"""Order audit history by ingestion and defend execution identities in PostgreSQL.

Existing duplicate execution identities intentionally make this migration fail:
the operator must reconcile that evidence, never silently discard it.
"""

from alembic import op
from sqlalchemy import text

from app.db.models import ENVIRONMENT_TABLE_NAMES, EXECUTION_UNIQUE_KEYS, SHARED_TABLE_NAMES

revision = "0002_durable_execution"
down_revision = "0001_initial"
branch_labels = None
depends_on = None


def upgrade() -> None:
    bind = op.get_bind()
    for schema, tables in (
        ("shared", SHARED_TABLE_NAMES),
        ("demo", ENVIRONMENT_TABLE_NAMES),
        ("live", ENVIRONMENT_TABLE_NAMES),
    ):
        for table in tables:
            bind.execute(
                text(
                    f'ALTER TABLE "{schema}"."{table}" ADD COLUMN IF NOT EXISTS '
                    "append_sequence BIGINT GENERATED BY DEFAULT AS IDENTITY"
                )
            )
            bind.execute(
                text(
                    f'CREATE INDEX IF NOT EXISTS "ix_{table}_append_sequence" '
                    f'ON "{schema}"."{table}" (append_sequence)'
                )
            )
        if schema == "shared":
            continue
        for table, keys in EXECUTION_UNIQUE_KEYS.items():
            for key in keys:
                bind.execute(
                    text(
                        f'CREATE UNIQUE INDEX IF NOT EXISTS "uq_{table}_{key}" '
                        f'ON "{schema}"."{table}" '
                        f"(environment, namespace, (payload ->> '{key}')) "
                        f"WHERE payload ->> '{key}' IS NOT NULL"
                    )
                )


def downgrade() -> None:
    bind = op.get_bind()
    for schema in ("demo", "live"):
        for table, keys in EXECUTION_UNIQUE_KEYS.items():
            for key in keys:
                bind.execute(text(f'DROP INDEX IF EXISTS "{schema}"."uq_{table}_{key}"'))
    for schema, tables in (
        ("shared", SHARED_TABLE_NAMES),
        ("demo", ENVIRONMENT_TABLE_NAMES),
        ("live", ENVIRONMENT_TABLE_NAMES),
    ):
        for table in tables:
            bind.execute(
                text(f'ALTER TABLE "{schema}"."{table}" DROP COLUMN IF EXISTS append_sequence')
            )
