"""Durable, bounded market-event handoff into the existing research pipeline."""

from __future__ import annotations

import asyncio
import math
import re
from datetime import UTC, datetime
from typing import Any, Literal, Protocol
from uuid import NAMESPACE_URL, UUID, uuid5

from pydantic import Field

from app.clock.base import Clock
from app.config import RuntimeBinding
from app.domain.enums import DemoBackend, ExecutionEnvironment
from app.domain.models import (
    EquityQuote,
    OptionQuote,
    SentinelEvent,
    TimestampedModel,
    TradeProposal,
    sha256_json,
)
from app.exceptions import DataInvalidError, SafetyCriticalError
from app.execution.postgres_store import ExecutionAuditRepository
from app.market.base import MarketDataProvider

_VERSION = "live-market-research-queue-v1"
_EVENT_TYPES = {"MARKET_BASELINE", "MARKET_MEASURED_CHANGE"}


class EventResearcher(Protocol):
    binding: RuntimeBinding

    async def on_event(
        self, event: SentinelEvent, market: MarketDataProvider
    ) -> TradeProposal | None: ...


class _Cursor(TimestampedModel):
    record_kind: Literal["live_market_research_cursor"] = "live_market_research_cursor"
    version: Literal["live-market-research-queue-v1"] = "live-market-research-queue-v1"
    environment: Literal["DEMO"] = "DEMO"
    namespace: str
    market_research_queue_key: str = Field(pattern=r"^[a-f0-9]{64}$")
    provider: str
    capability_version: str
    event_sequence: int = Field(gt=0, strict=True)
    event_id: UUID
    event_hash: str = Field(pattern=r"^[a-f0-9]{64}$")


def _aware(value: Any) -> datetime:
    if isinstance(value, str):
        value = datetime.fromisoformat(value.replace("Z", "+00:00"))
    if not isinstance(value, datetime) or value.tzinfo is None or value.utcoffset() is None:
        raise DataInvalidError("market research requires aware timestamps")
    return value.astimezone(UTC)


class LiveMarketResearchQueue:
    """One oldest pending event per tick, with no execution or broker authority.

    The environment's single-instance lock remains mandatory. The local lock
    serializes calls, not processes. A full newest-first page that does not reach
    the saved cursor cannot prove a complete pending prefix and fails visibly.
    There is no infinite history scan and no newest-first event loss.

    CandidateResearchWorker supplies durable event-id idempotency. Its terminal
    record must exist before the queue checkpoint is appended. An interrupted or
    ambiguous checkpoint write is retried from persisted state on the next tick;
    no candidate is regenerated by this queue and no proposal is dispatched.

    Equity and option baseline/change events all count toward the 1000-row
    window. An initial watchlist with very large option chains can exceed that
    window and fails explicitly; this queue does not silently drop baselines or
    enlarge the configured watchlist. Deploy with a deliberately small explicit
    surveillance scope and monitor pending-prefix failures.
    """

    def __init__(
        self,
        repository: ExecutionAuditRepository,
        clock: Clock,
        market: MarketDataProvider,
        researcher: EventResearcher,
        *,
        maximum_records: int = 1000,
        maximum_seconds: float = 200,
    ) -> None:
        if (
            isinstance(maximum_records, bool)
            or not isinstance(maximum_records, int)
            or not 1 <= maximum_records <= 1000
            or isinstance(maximum_seconds, bool)
            or not isinstance(maximum_seconds, (int, float))
            or not math.isfinite(maximum_seconds)
            or not 0 < maximum_seconds <= 200
        ):
            raise ValueError("market research queue requires bounded finite limits")
        self.repository, self.clock, self.market, self.researcher = (
            repository,
            clock,
            market,
            researcher,
        )
        self.binding = repository.binding
        self._identity, self._capability_version = market.identity, market.capability_version
        self.maximum_records, self.maximum_seconds = maximum_records, maximum_seconds
        self._key = sha256_json(
            {
                "version": _VERSION,
                "environment": self.binding.environment.value,
                "namespace": self.binding.idempotency_namespace,
                "provider": self._identity,
                "capability_version": self._capability_version,
            }
        )
        self._lock = asyncio.Lock()
        self._guard()

    def _guard(self) -> None:
        if (
            self.repository.binding != self.binding
            or self.researcher.binding != self.binding
            or self.binding.environment is not ExecutionEnvironment.DEMO
            or self.binding.demo_backend is not DemoBackend.BROKER_SHADOW
            or self.binding.external_write_authority
            or not self.binding.idempotency_namespace
        ):
            raise SafetyCriticalError("market research queue requires no-write DEMO/BROKER_SHADOW")
        if (
            not self._identity.strip()
            or not self._capability_version.strip()
            or self.market.identity != self._identity
            or self.market.capability_version != self._capability_version
            or self.market.capabilities.replay
            or not self.market.capabilities.equity_quotes
            or not self.market.capabilities.option_chains
        ):
            raise SafetyCriticalError("market research provider identity/capabilities changed")

    def _payload(self, row: dict[str, Any], *, shared: bool = False) -> dict[str, Any]:
        expected_environment = None if shared else self.binding.environment.value
        expected_namespace = None if shared else self.binding.idempotency_namespace
        if (
            row.get("environment") != expected_environment
            or row.get("namespace") != expected_namespace
        ):
            raise SafetyCriticalError(
                "market research read crossed its environment/namespace binding"
            )
        payload = row.get("payload")
        if not isinstance(payload, dict):
            raise DataInvalidError("market research audit payload is invalid")
        if (
            payload.get("environment") != self.binding.environment.value
            or payload.get("namespace") != self.binding.idempotency_namespace
        ):
            raise SafetyCriticalError(
                "market research payload crossed its environment/namespace binding"
            )
        return payload

    def _event(self, row: dict[str, Any]) -> SentinelEvent:
        payload = self._payload(row)
        event = SentinelEvent.model_validate(
            {
                key: value
                for key, value in payload.items()
                if key not in {"environment", "namespace"}
            }
        )
        baseline = event.event_type == "MARKET_BASELINE"
        metadata = event.payload
        if (
            event.event_type not in _EVENT_TYPES
            or event.source != self._identity
            or metadata.get("provider") != self._identity
            or metadata.get("capability_version") != self._capability_version
            or metadata.get("worker_version") != "live-read-surveillance-v1"
            or metadata.get("data_mode") != "LIVE_READ"
            or metadata.get("quote_kind") not in {"equity", "option"}
            or metadata.get("baseline") is not baseline
            or event.severity != (0 if baseline else 1)
            or not isinstance(metadata.get("changes"), dict)
            or bool(metadata["changes"]) == baseline
            or len(event.tickers) != 1
            or re.fullmatch(r"[A-Z0-9][A-Z0-9.-]{0,11}", event.tickers[0]) is None
            or len(event.raw_reference_ids) != (1 if baseline else 2)
            or len(set(event.raw_reference_ids)) != len(event.raw_reference_ids)
            or _aware(event.effective_at) > event.created_at
            or _aware(row["created_at"]) != event.created_at
        ):
            raise DataInvalidError("market event failed queue provenance validation")
        for reference in event.raw_reference_ids:
            UUID(reference)
        return event

    async def _verify_snapshot(self, event: SentinelEvent, now: datetime) -> None:
        match = re.fullmatch(
            r"live-read:([a-f0-9]{64}):([a-f0-9]{64}):event", event.deduplication_key
        )
        if match is None:
            raise DataInvalidError("market event has an invalid observation identity")
        observation_key = event.deduplication_key.removesuffix(":event")
        option = event.payload["quote_kind"] == "option"
        row = await self.repository.find_payload(
            "option_snapshots" if option else "market_snapshots", "observation_key", observation_key
        )
        if row is None:
            raise DataInvalidError("market event is missing its durable observation")
        payload = self._payload(row, shared=True)
        quote = (OptionQuote if option else EquityQuote).model_validate(payload.get("quote"))
        symbol = quote.contract.symbol if isinstance(quote, OptionQuote) else quote.symbol
        stream = (
            f"option:{quote.contract.instrument_id}"
            if isinstance(quote, OptionQuote)
            else f"equity:{symbol}"
        )
        if (
            payload.get("worker_version") != "live-read-surveillance-v1"
            or payload.get("data_mode") != "LIVE_READ"
            or payload.get("observation_key") != observation_key
            or payload.get("surveillance_key") != match[1]
            or payload.get("stream_key") != stream
            or sha256_json(quote.model_dump(mode="json", exclude={"snapshot_id"})) != match[2]
            or quote.snapshot_id != uuid5(NAMESPACE_URL, observation_key)
            or event.event_id != uuid5(NAMESPACE_URL, event.deduplication_key)
            or event.raw_reference_ids[-1] != str(quote.snapshot_id)
            or SentinelEvent.model_validate(payload.get("event")) != event
            or quote.metadata.provider != self._identity
            or quote.metadata.capability_version != self._capability_version
            or event.tickers != (symbol,)
            or event.effective_at != quote.metadata.effective_at
            or _aware(payload.get("created_at")) != event.created_at
            or _aware(row["created_at"]) != event.created_at
            or not quote.metadata.effective_at
            <= quote.metadata.observed_at
            <= event.created_at
            <= now
        ):
            raise DataInvalidError("market event does not match its durable observation")

    async def _cursor(self, now: datetime) -> int:
        row = await self.repository.find_payload(
            "system_runs", "market_research_queue_key", self._key
        )
        if row is None:
            return 0
        cursor = _Cursor.model_validate(self._payload(row))
        if (
            cursor.provider != self._identity
            or cursor.capability_version != self._capability_version
            or cursor.market_research_queue_key != self._key
            or cursor.created_at > now
            or _aware(row["created_at"]) != cursor.created_at
        ):
            raise SafetyCriticalError("market research checkpoint provenance or clock is invalid")
        event_row = await self.repository.find_payload(
            "sentinel_events", "event_id", str(cursor.event_id)
        )
        if event_row is None or event_row.get("append_sequence") != cursor.event_sequence:
            raise SafetyCriticalError(
                "market research checkpoint cannot prove its journal position"
            )
        event = self._event(event_row)
        if (
            event.created_at > cursor.created_at
            or sha256_json(event.model_dump(mode="json")) != cursor.event_hash
        ):
            raise SafetyCriticalError("market research checkpoint event content changed")
        return cursor.event_sequence

    async def _verify_research_result(
        self, event: SentinelEvent, proposal: TradeProposal | None
    ) -> None:
        row = await self.repository.find_payload(
            "candidate_runs", "event_key", f"{self.binding.idempotency_namespace}:{event.event_id}"
        )
        if row is None:
            raise SafetyCriticalError("research must be durable before advancing its queue")
        payload = self._payload(row)
        saved = (
            TradeProposal.model_validate(payload["proposal"])
            if payload.get("proposal") is not None
            else None
        )
        if (
            payload.get("event_hash") != sha256_json(event.model_dump(mode="json"))
            or payload.get("status") != ("PROPOSED" if proposal is not None else "WAIT")
            or saved != proposal
            or _aware(payload.get("created_at")) > _aware(self.clock.now())
        ):
            raise SafetyCriticalError("research result lacks matching terminal durable evidence")
        if proposal is not None and (
            proposal.environment is not self.binding.environment
            or proposal.namespace != self.binding.idempotency_namespace
            or proposal.created_at > self.clock.now()
        ):
            raise SafetyCriticalError("research proposal crossed its namespace or causal boundary")

    async def tick(self) -> TradeProposal | None:
        async with self._lock, asyncio.timeout(self.maximum_seconds):
            self._guard()
            now = _aware(self.clock.now())
            cursor = await self._cursor(now)
            rows = await self.repository.list_payloads(
                "sentinel_events", filters={"source": self._identity}, limit=self.maximum_records
            )
            if len(rows) > self.maximum_records:
                raise SafetyCriticalError("market research scan exceeded its bound")
            sequences: set[int] = set()
            for row in rows:
                self._payload(row)
                sequence = row.get("append_sequence")
                if (
                    isinstance(sequence, bool)
                    or not isinstance(sequence, int)
                    or sequence <= 0
                    or sequence in sequences
                ):
                    raise SafetyCriticalError(
                        "market research requires unique positive journal sequences"
                    )
                sequences.add(sequence)
            if len(rows) == self.maximum_records and min(sequences) > cursor:
                raise SafetyCriticalError(
                    "market research pending prefix exceeds its bounded scan; no events skipped"
                )
            pending = [
                row
                for row in rows
                if row["append_sequence"] > cursor
                and row["payload"].get("event_type") in _EVENT_TYPES
            ]
            if not pending:
                return None
            row = min(pending, key=lambda item: item["append_sequence"])
            event = self._event(row)
            if event.created_at > now or _aware(event.effective_at) > now:
                return None  # Preserve the pending prefix instead of skipping future events.
            await self._verify_snapshot(event, now)
            proposal = await self.researcher.on_event(event, self.market)
            self._guard()
            await self._verify_research_result(event, proposal)
            await self.repository.append(
                "system_runs",
                _Cursor(
                    created_at=_aware(self.clock.now()),
                    namespace=self.binding.idempotency_namespace,
                    market_research_queue_key=self._key,
                    provider=self._identity,
                    capability_version=self._capability_version,
                    event_sequence=row["append_sequence"],
                    event_id=event.event_id,
                    event_hash=sha256_json(event.model_dump(mode="json")),
                ),
            )
            return proposal
